- name: Clone git repo
  git:
    repo: "https://github.com/yeshwanthlm/django-on-ec2.git"
    dest: "{{ project_dir }}"
    force: yes

- name: Install python3-venv
  apt:
    name: python3-venv
    state: present

- name: Change permissions of manage.py
  file:
    path: "{{ project_dir }}/manage.py"
    mode: '0755'

- name: Create a virtual environment inside the project directory
  shell: python3 -m venv virtualenv
  args:
    chdir: "{{ project_dir }}"

- name: Activate venv
  shell: ". {{ venv_dir }}/bin/activate"
  args:
    executable: /bin/bash

- name: Upgrade pip
  shell: "{{ venv_dir }}/bin/pip install --upgrade pip"

- name: Install django
  shell: "{{ venv_dir }}/bin/pip install django"
  args:
    executable: /bin/bash

- name: Make migrations
  shell: "{{ venv_dir }}/bin/python manage.py makemigrations"
  args:
    chdir: "{{ project_dir }}"
    executable: /bin/bash

- name: Apply migrations
  shell: "{{ venv_dir }}/bin/python manage.py migrate"
  args:
    chdir: "{{ project_dir }}"
    executable: /bin/bash

- name: Run the Django application
  shell: "nohup {{ venv_dir }}/bin/python manage.py runserver 0.0.0.0:8000 &"
  args:
    chdir: "{{ project_dir }}"
    executable: /bin/bash
